Fix `svn_switch -`

diff --git a/svn/svn_switch b/svn/svn_switch
--- a/svn/svn_switch
+++ b/svn/svn_switch
@@ -9,12 +9,9 @@ svn info > /dev/null 2>&1
 
 function switchBranch()
 {
-	echo $(svn info | grep ^URL | awk -F\/ '{print $NF}' | sed 's/FS%20//') > ~/.svn_last_branch.tmp # Cache our current branch
-
 	if [ $1 = "trunk" ]; then
 		svn switch "http://svn.excelsystems.com/svn/websmart/websmart/trunk" 2> /dev/null
 	else
-
 		if [ $1 = "-" ]; then
 			svn_switch $(cat ~/.svn_last_branch.tmp)
 		else
@@ -25,6 +22,8 @@ function switchBranch()
 
 ### Main
 
+LastBranch=$(svn_current_branch.sh)
+
 switchBranch "$1"
 
 if [ $? -ne 0 ]; then
@@ -33,20 +32,22 @@ if [ $? -ne 0 ]; then
 
 	Confirm
 
-	if [ $Confirm -eq 0 ]; then
+	if [ $Confirm -eq 0 ]; then  # We decided to create a new branch
 		powershell svn_branch.ps1 "$1"
 	else
 		echo "Aborting"
 		exit 1
 	fi
 
-	if [ $? -ne 0 ]; then
+	if [ $? -ne 0 ]; then  # Branch creation failed
 		echo "Branch creation failed, something has gone horribly wrong."
 		exit 1
-	else
+	else  # We created a new branch and are switching to it
 		switchBranch "$1"
+		echo $LastBranch > ~/.svn_last_branch.tmp
 	fi
-
+else  # we sucessfully switched, write the last branch number out
+		echo $LastBranch > ~/.svn_last_branch.tmp
 fi
 
 # Finally, whatever the result, update the branch we're currently on
